import { v4 as uuid } from 'uuid'
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [{
        _id: uuid(),
        title: 'Super Mario',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/SuperMario.jpg?raw=true',
        price: 2999,
        oldPrice: 3999,
        discount: '25%',
        categoryName: 'Adventure',
        rating: 4.6,
    },
    {
        _id: uuid(),
        title: 'Call of Duty',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/call_of_duty.jpg?raw=true',
        price: 5999,
        oldPrice: 6999,
        discount: '20%',
        categoryName: 'Action',
        rating: 4.8,
    },
    {
        _id: uuid(),
        title: 'Gta V',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/GtaV.jpg?raw=true',
        price: 9999,
        oldPrice: 12999,
        discount: '35%',
        categoryName: 'Arcade',
        rating: 3.1,
    },
    {
        _id: uuid(),
        title: 'Valorant',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/valorant.jpg?raw=true',
        price: 1999,
        oldPrice: 4999,
        discount: '35%',
        categoryName: 'Sports',
        rating: 3.5,
    },
    {
        _id: uuid(),
        title: 'Minecraft',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/Minecraft.png?raw=true',
        price: 999,
        oldPrice: 2999,
        discount: '45%',
        categoryName: 'Strategy',
        rating: 2.2,
    },
    {
        _id: uuid(),
        title: 'Max Payne 3',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/Max_Payne_3.jpg?raw=true',
        price: 4999,
        oldPrice: 7999,
        discount: '30%',
        categoryName: 'Action',
        rating: 3.6,
    },
    {
        _id: uuid(),
        title: 'Fifa',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/fifa.png?raw=true',
        price: 2999,
        oldPrice: 3999,
        discount: '25%',
        categoryName: 'Sports',
        rating: 2.8,
    },
    {
        _id: uuid(),
        title: 'Cs Go',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/cs%20go.jpg?raw=true',
        price: 3999,
        oldPrice: 6999,
        discount: '25%',
        categoryName: 'Sports',
        rating: 1.4,
    },
    {
        _id: uuid(),
        title: 'SanAndreas',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/sanandreas.jpg?raw=true',
        price: 1999,
        oldPrice: 2999,
        discount: '25%',
        categoryName: 'Arcade',
        rating: 2.9,
    },
    {
        _id: uuid(),
        title: 'Dota 2',
        img: 'https://raw.githubusercontent.com/Rohitprasad83/images-setup/dev/E-com/Dota%202.webp',
        price: 1999,
        oldPrice: 2999,
        discount: '25%',
        categoryName: 'Strategy',
        rating: 3.7,
    },
    {
        _id: uuid(),
        title: 'Far Cry 3',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/Far%20Cry%203.jpg?raw=true',
        price: 1999,
        oldPrice: 2999,
        discount: '25%',
        categoryName: 'Adventure',
        rating: 4.8,
    },
    {
        _id: uuid(),
        title: 'God of War 2',
        img: 'https://github.com/Rohitprasad83/images-setup/blob/dev/E-com/godofwar2.png?raw=true',
        price: 1999,
        oldPrice: 2999,
        discount: '25%',
        categoryName: 'Arcade',
        rating: 1.9,
    },
]